# Server settings
server:
  port: "8080"
  mode: "debug" # debug, release, test

# Database settings (PostgreSQL)
database:
  host: "localhost"
  port: "5432"
  user: "learngo"
  password: "learngo"
  dbname: "learngo"
  sslmode: "disable"

# JWT settings
jwt:
  secret: "your_very_secret_key"
  issuer: "LearnGo"
  expire_hours: 24

# Redis settings (for caching or temporary data like live chat)
redis:
  addr: "localhost:6379"
  password: ""
  db: 0

# Alibaba Cloud OSS settings
oss:
  endpoint: "your_oss_endpoint" # e.g., oss-cn-hangzhou.aliyuncs.com
  access_key_id: "your_access_key_id"
  access_key_secret: "your_access_key_secret"
  bucket_name: "your_bucket_name"
